// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbzrnxojrdbugoozjjjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxienJueG9qcmRidWdvb3pqampjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODM5OTQsImV4cCI6MjA2ODE1OTk5NH0.gTb74hB-7li5fOlYAH50V1Z5WcE0TSm3caOL9lJIqTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});